name: CI

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  cpplint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install cpplint
        run: pip3 install cpplint
      - name: Lint C++ files
        run: |
          cd src
          echo "filter=-build/c++11, -legal/copyright, -build/namespaces_literals, -runtime/references,
                linelength=120" > CPPLINT.cfg
          cpplint --recursive .

  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          mkdir build
          cd build
          pip3 install conan==1.*
          conan install .. --build=missing -s build_type=${{env.BUILD_TYPE}} -s compiler.libcxx=libstdc++11

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target parser_test

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --extra-verbose